name: Node CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install TypeScript globally
        run: npm install -g typescript
      - name: Install Angular CLI globally
        run: npm install -g @angular/cli
      - name: npm install, build, test
        run: |
          npm ci
          npm run build --if-present
          npm run build:test --if-present
          npm run test:unit
          npm run test
      - name: npm install, build, test with v12
        run: |
          npm ci
          npm run build --if-present
          npm run test:v12
        env:
          CI: true
